export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const NO_REPOS = "NO_REPOS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const GET_ALL_BLOG_BY_FOLLOWING = "GET_ALL_BLOG_BY_FOLLOWING";
export const GET_ALL_BLOG_BY_SINGLE_FOLLOWING_MANUFACTURER =
  "GET_ALL_BLOG_BY_SINGLE_FOLLOWING_MANUFACTURER";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

//user/manufacturer types
export const FOLLOW_MANUFACTURER = "FOLLOW_MANUFACTURER";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const FOLLOW_ERROR = "FOLLOW_ERROR";
export const GET_ALL_MANUFACTURER ="GET_ALL_MANUFACTURER"
export const GET_SINGLE_MANUFACTURER = "GET_SINGLE_MANUFACTURER"
export const MANUFACTURER_ERROR = "MANUFACTURER_ERROR"
//user types

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

//CHAT

export const CURRENT_CHAT = "CURRENT_CHAT";
export const CONVERSATION = "CONVERSATION";


// QUESTION

export const QUESTION_ADDED_SUCCESFULLY = "QUESTION_ADDED_SUCCESFULLY"
export const ANSWER_ADDED_SUCCESFULLY = "ANSWER_ADDED_SUCCESFULLY"
export const QUESTION_ERROR = "QUESTION_ERROR"
export const GET_QUESTIONS = "GET_QUESTIONS"

//ADMIN
export const ADMIN_PRODUCTS = "ADMIN_PRODUCTS"
export const ADMIN_PRODUCT_ERROR = "ADMIN_PRODUCT_ERROR"
export const ADMIN_BLOGS = "ADMIN_BLOGS"
export const ADMIN_BLOG_ERROR = "ADMIN_BLOG_ERROR"
export const ADMIN_BLOG_ADDED = "ADMIN_BLOG_ADDED"
export const REVIEWS_ADMIN = "REVIEWS_ADMIN"
export const REVIEWS_ADMIN_ERROR = "REVIEWS_ADMIN_ERROR"