### First Stage ###
FROM node:14-slim AS builder

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .
ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

# RUN npm run build

CMD ["node_modules/.bin/next", "start"]

# RUN npm run start


### Second Stage ###
FROM caddy:2.1.1

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

EXPOSE 80

EXPOSE 443 
