version: "3.0"
services:
  react-app:
    image: react-app-dev
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  server:
    image: server
    env_file: ./server/.env
    ports:
      - "5000:5000"
    networks:
      - server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - server
    volumes:
      - mongo-data:/data/db
networks:
  server:
    driver: bridge
volumes:
  mongo-data:
    driver: local