version: "3"
services:
  react-app: 
    build: ./
    image: react-app-production:production
  nginx-image: 
    image: nginx-image
    build: ./frontend/nginx
    ports:
      - 80:80
  server :
    image: server 
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./Server/.env
    ports:
      - "5000:5000"
    networks:
      - server
networks:
  server:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local 
