version: "3"
services:
  react-app:
    image: react-app-production:production
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - server
  server :
    image: server 
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./Server/.env
    ports:
      - "5000:5000"
    networks:
      - server
networks:
  server:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local 