version: "3"
services:
  react-app: 
    build: ./frontend
    image: react-app-production:production
    ports:
      - 3000:3000
  nginx-image: 
    image: nginx-image
    build: ./frontend/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - react-app 
  server :
    image: server 
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./Server/.env
    ports:
      - "4000:4000"
    networks:
      - server
networks:
  server:
    driver: bridge