version: "3"
services:
  react-app: 
    build: ./frontend
    image: react-app-production:production
    ports:
      - 3000:3000
  nginx-image: 
    image: nginx-image
    build: ./frontend/nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - react-app 
        - api
  api:
    build: ./Server
    image: api
    restart: on-failure
    ports:
      - "4000:4000"
    env_file: ./Server/.env